import type { Metadata } from "next";
import { Roboto_Mono, Inter } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";
import { Navbar } from "@/components/layout/navbar";
import "./globals.css";

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

const interSans = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Lexend:wght@100..900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${interSans.variable} ${robotoMono.variable} antialiased`}>
        <Navbar />
        {/* <main className="max-w-7xl justify-self-center">{children}</main> */}
        <main className="container mx-auto">{children}</main>
        <Toaster />
      </body>
    </html>
  );
}
